package org.hoteldanncarlton.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-16T01:38:01.161-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "HotelDannCarltonService",
                  wsdlLocation = "file:/D:/oxygen/eclipse-workspace/hotelDanCarltonSOAPService/src/main/resources/wsdl/hoteldanncarlton.wsdl",
                  targetNamespace = "http://www.hoteldanncarlton.org/demo/")
public class HotelDannCarltonService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.hoteldanncarlton.org/demo/", "HotelDannCarltonService");
    public final static QName HotelDannCarltonServicesEndpoint = new QName("http://www.hoteldanncarlton.org/demo/", "HotelDannCarltonServicesEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/oxygen/eclipse-workspace/hotelDanCarltonSOAPService/src/main/resources/wsdl/hoteldanncarlton.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HotelDannCarltonService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/oxygen/eclipse-workspace/hotelDanCarltonSOAPService/src/main/resources/wsdl/hoteldanncarlton.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HotelDannCarltonService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HotelDannCarltonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelDannCarltonService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HotelDannCarltonService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HotelDannCarltonService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HotelDannCarltonService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HotelDannCarltonSystemServices
     */
    @WebEndpoint(name = "HotelDannCarltonServicesEndpoint")
    public HotelDannCarltonSystemServices getHotelDannCarltonServicesEndpoint() {
        return super.getPort(HotelDannCarltonServicesEndpoint, HotelDannCarltonSystemServices.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelDannCarltonSystemServices
     */
    @WebEndpoint(name = "HotelDannCarltonServicesEndpoint")
    public HotelDannCarltonSystemServices getHotelDannCarltonServicesEndpoint(WebServiceFeature... features) {
        return super.getPort(HotelDannCarltonServicesEndpoint, HotelDannCarltonSystemServices.class, features);
    }

}
