package org.example.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-10T22:46:25.264-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.example.org/demo/", name = "HotelDannCarltonSystemServices")
@XmlSeeAlso({ObjectFactory.class})
public interface HotelDannCarltonSystemServices {

    @WebMethod
    @RequestWrapper(localName = "realizarReserva", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.RealizarReserva")
    @ResponseWrapper(localName = "realizarReservaResponse", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.RealizarReservaResponse")
    public void realizarReserva(
        @WebParam(name = "nroReserva", targetNamespace = "")
        java.lang.String nroReserva,
        @WebParam(name = "habitacion", targetNamespace = "")
        java.lang.String habitacion,
        @WebParam(name = "hotel", targetNamespace = "")
        java.lang.String hotel,
        @WebParam(mode = WebParam.Mode.INOUT, name = "fechaReserva", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaReserva,
        @WebParam(name = "fechaIngreso", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fechaIngreso,
        @WebParam(name = "nroHabitaciones", targetNamespace = "")
        java.math.BigInteger nroHabitaciones,
        @WebParam(name = "tipoHabitacion", targetNamespace = "")
        java.lang.String tipoHabitacion,
        @WebParam(name = "cantidadPersonas", targetNamespace = "")
        java.math.BigInteger cantidadPersonas,
        @WebParam(name = "estadoReserva", targetNamespace = "")
        java.lang.String estadoReserva,
        @WebParam(name = "residentes", targetNamespace = "")
        org.example.demo.RealizarReserva.Residentes residentes,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> respuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerReserva", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.ObtenerReserva")
    @ResponseWrapper(localName = "obtenerReservaResponse", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.ObtenerReservaResponse")
    public void obtenerReserva(
        @WebParam(name = "idReserva", targetNamespace = "")
        java.lang.String idReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "nroReserva", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> nroReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "habitacion", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> habitacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "hotel", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> hotel,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaReserva", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaIngreso", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaIngreso,
        @WebParam(mode = WebParam.Mode.OUT, name = "nroHabitaciones", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> nroHabitaciones,
        @WebParam(mode = WebParam.Mode.OUT, name = "tipoHabitacion", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> tipoHabitacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "cantidadPersonas", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigInteger> cantidadPersonas,
        @WebParam(mode = WebParam.Mode.OUT, name = "estadoReserva", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estadoReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "residentes", targetNamespace = "")
        javax.xml.ws.Holder<org.example.demo.ObtenerReservaResponse.Residentes> residentes
    );

    @WebMethod
    @RequestWrapper(localName = "cancelarReserva", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.CancelarReserva")
    @ResponseWrapper(localName = "cancelarReservaResponse", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.CancelarReservaResponse")
    public void cancelarReserva(
        @WebParam(name = "idReserva", targetNamespace = "")
        java.lang.String idReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> respuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaReserva", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaReserva
    );
}
